import { VersionInfo } from '@start9labs/start-sdk'

export const v0_2_6 = VersionInfo.of({
  version: '0.2.6:0',
  releaseNotes: {
    en_US:
      'The proof-of-work verification now plays full screen. Pressing Verify on the best-share page takes over the display and walks the whole proof in eight chapters: rebuilding the merkle root from the coinbase transaction and its branch hashes, padding the header into two 512-bit message blocks, seeding the eight hash registers, then the compression rounds themselves, where a live grid shows all 256 bits of the working state flipping, every lit cell a real bit of your share’s computation, followed by the second hash, the byte reversal, and the comparison against the share and network targets. It ends on the block header hash with its leading zeros lit. The formulas are set in proper mathematical notation, and every scene that uses colour carries a legend. Nothing is simulated: all of it comes from hashing your own share in your browser. Playback can be paused, run at 2× or 4×, or skipped straight to the result; Escape closes it and Space pauses. The raw header section now also explains why that data is worth having: a screenshot of a big difficulty number proves nothing, but the 80 bytes behind it are the share hash’s exact preimage, and because they commit to the previous block and to the coinbase transaction that pays you, the proof cannot be lifted from another miner or replayed from a different block.',
    es_ES:
      'La verificación de la prueba de trabajo ahora se reproduce a pantalla completa. Al pulsar Verificar en la página de mejores participaciones, la animación ocupa toda la pantalla y recorre la prueba entera en ocho capítulos: la reconstrucción de la raíz de Merkle a partir de la transacción coinbase y sus hashes de rama, el relleno de la cabecera en dos bloques de mensaje de 512 bits, la inicialización de los ocho registros de hash y luego las propias rondas de compresión, donde una cuadrícula en vivo muestra los 256 bits del estado de trabajo cambiando, y cada celda encendida es un bit real del cálculo de su participación, seguidas del segundo hash, la inversión de bytes y la comparación con los objetivos de la participación y de la red. Termina en el hash de la cabecera del bloque con sus ceros iniciales iluminados. Las fórmulas aparecen en notación matemática propiamente compuesta y cada escena que usa color incluye una leyenda. Nada está simulado: todo procede de aplicar el hash a su propia participación en su navegador. La reproducción se puede pausar, acelerar a 2× o 4×, o saltar directamente al resultado; Esc la cierra y la barra espaciadora la pausa. La sección de la cabecera en bruto explica ahora por qué merece la pena tener esos datos: una captura de pantalla con un número de dificultad grande no demuestra nada, pero los 80 bytes que hay detrás son la preimagen exacta del hash de la participación y, como se comprometen con el bloque anterior y con la transacción coinbase que le paga a usted, la prueba no puede tomarse de otro minero ni reutilizarse desde otro bloque.',
    de_DE:
      'Die Arbeitsnachweis-Überprüfung läuft jetzt im Vollbild. Ein Klick auf „Überprüfen“ auf der Bestwert-Seite übernimmt den Bildschirm und führt in acht Kapiteln durch den gesamten Nachweis: den Neuaufbau der Merkle-Wurzel aus der Coinbase-Transaktion und ihren Zweig-Hashes, das Auffüllen des Headers zu zwei 512-Bit-Nachrichtenblöcken, das Initialisieren der acht Hash-Register und dann die Kompressionsrunden selbst, wobei ein Live-Raster alle 256 Bits des Arbeitszustands beim Umkippen zeigt und jede leuchtende Zelle ein echtes Bit der Berechnung Ihres Shares ist, gefolgt vom zweiten Hash, der Byte-Umkehrung und dem Vergleich mit dem Share- und dem Netzwerk-Ziel. Es endet beim Blockheader-Hash mit hervorgehobenen führenden Nullen. Die Formeln sind in korrekter mathematischer Notation gesetzt, und jede Szene mit Farbcodierung hat eine Legende. Nichts ist simuliert: Alles stammt daraus, Ihren eigenen Share in Ihrem Browser zu hashen. Die Wiedergabe lässt sich pausieren, mit 2× oder 4× abspielen oder direkt zum Ergebnis überspringen; Esc schließt sie, die Leertaste pausiert. Der Abschnitt mit dem rohen Header erklärt nun auch, warum diese Daten wertvoll sind: Ein Screenshot mit einer großen Schwierigkeitszahl beweist nichts, aber die 80 Bytes dahinter sind das exakte Urbild des Share-Hashes, und da sie sich auf den vorherigen Block und auf die Coinbase-Transaktion festlegen, die an Sie zahlt, lässt sich der Nachweis weder von einem anderen Miner übernehmen noch aus einem anderen Block wiederverwenden.',
    pl_PL:
      'Weryfikacja dowodu pracy jest teraz odtwarzana na pełnym ekranie. Naciśnięcie „Zweryfikuj” na stronie najlepszych udziałów przejmuje ekran i prowadzi przez cały dowód w ośmiu rozdziałach: odbudowa korzenia Merkle z transakcji coinbase i jej haszy gałęzi, uzupełnienie nagłówka do dwóch 512-bitowych bloków wiadomości, zainicjowanie ośmiu rejestrów skrótu, a następnie same rundy kompresji, gdzie żywa siatka pokazuje wszystkie 256 bitów stanu roboczego w trakcie zmian, a każda zapalona komórka to prawdziwy bit obliczeń Twojego udziału, po czym drugie haszowanie, odwrócenie bajtów i porównanie z celem udziału oraz celem sieci. Kończy się na haszu nagłówka bloku z podświetlonymi wiodącymi zerami. Wzory zapisano w prawidłowej notacji matematycznej, a każda scena używająca kolorów ma legendę. Nic nie jest symulowane: wszystko pochodzi z haszowania Twojego własnego udziału w przeglądarce. Odtwarzanie można wstrzymać, przyspieszyć do 2× lub 4× albo przeskoczyć wprost do wyniku; Esc zamyka, a spacja wstrzymuje. Sekcja surowego nagłówka wyjaśnia teraz również, dlaczego te dane mają wartość: zrzut ekranu z dużą liczbą trudności niczego nie dowodzi, ale stojące za nim 80 bajtów to dokładny przeciwobraz hasza udziału, a ponieważ wiążą się z poprzednim blokiem i z transakcją coinbase wypłacającą Tobie, dowodu nie da się przejąć od innego górnika ani odtworzyć z innego bloku.',
    fr_FR:
      'La vérification de la preuve de travail s’affiche désormais en plein écran. Un clic sur Vérifier depuis la page des meilleures parts prend possession de l’écran et parcourt toute la preuve en huit chapitres : la reconstruction de la racine de Merkle à partir de la transaction coinbase et de ses hachages de branche, le remplissage de l’en-tête en deux blocs de message de 512 bits, l’initialisation des huit registres de hachage, puis les tours de compression eux-mêmes, où une grille en direct montre les 256 bits de l’état de travail en train de basculer, chaque cellule allumée étant un bit réel du calcul de votre part, suivis du second hachage, de l’inversion des octets et de la comparaison avec la cible de la part et celle du réseau. Cela se termine sur le hachage de l’en-tête de bloc, zéros de tête mis en lumière. Les formules sont composées en notation mathématique correcte, et chaque scène utilisant la couleur comporte une légende. Rien n’est simulé : tout provient du hachage de votre propre part dans votre navigateur. La lecture peut être mise en pause, lancée à 2× ou 4×, ou passée directement au résultat ; Échap ferme et la barre d’espace met en pause. La section de l’en-tête brut explique désormais aussi pourquoi ces données comptent : une capture d’écran affichant une grande difficulté ne prouve rien, mais les 80 octets qui la sous-tendent sont la préimage exacte du hachage de la part et, puisqu’ils engagent le bloc précédent ainsi que la transaction coinbase qui vous paie, la preuve ne peut être reprise d’un autre mineur ni rejouée depuis un autre bloc.',
  },
  // No data migration in either direction. Presentation only, the change
  // is confined to the dashboard bundled in the service binary, and it
  // reads nothing it was not already reading.
  migrations: {},
})
