import { VersionInfo } from '@start9labs/start-sdk'

export const v0_2_5 = VersionInfo.of({
  version: '0.2.5:0',
  releaseNotes: {
    en_US:
      'The estimated difficulty adjustment on the dashboard is now accurate from the very start of a retarget period. It was measuring elapsed time up to the current moment while counting only completed blocks, so the wait since the last block, ten minutes on average, was counted as mining time that had produced nothing. A few blocks into a period that wait is most of the sample, which is why the figure was wildly off early on and only settled down around the halfway mark. It now measures between block timestamps, matching what mempool.space shows. The estimated time until the adjustment is projected at the pace the network is actually keeping this period, rather than assuming a flat ten minutes per block.',
    es_ES:
      'El ajuste de dificultad estimado en el panel ahora es preciso desde el comienzo mismo del periodo de reajuste. Antes medía el tiempo transcurrido hasta el momento actual pero contaba solo los bloques completados, de modo que la espera desde el último bloque, diez minutos de media, se contabilizaba como tiempo de minado que no había producido nada. A los pocos bloques de iniciarse un periodo, esa espera representa la mayor parte de la muestra, por lo que la cifra se desviaba muchísimo al principio y solo se estabilizaba hacia la mitad. Ahora se mide entre las marcas de tiempo de los bloques, igual que muestra mempool.space. El tiempo estimado hasta el ajuste se proyecta al ritmo que la red lleva realmente en este periodo, en lugar de suponer diez minutos fijos por bloque.',
    de_DE:
      'Die geschätzte Schwierigkeitsanpassung im Dashboard ist jetzt schon zu Beginn einer Anpassungsperiode genau. Zuvor wurde die verstrichene Zeit bis zum aktuellen Moment gemessen, aber nur abgeschlossene Blöcke gezählt, die Wartezeit seit dem letzten Block, im Mittel zehn Minuten, floss also als Mining-Zeit ein, die nichts hervorgebracht hatte. Wenige Blöcke nach Beginn einer Periode macht diese Wartezeit den Großteil der Stichprobe aus, weshalb der Wert anfangs stark abwich und sich erst etwa zur Halbzeit einpendelte. Nun wird zwischen den Zeitstempeln der Blöcke gemessen, so wie es auch mempool.space anzeigt. Die geschätzte Zeit bis zur Anpassung wird mit dem Tempo hochgerechnet, das das Netzwerk in dieser Periode tatsächlich hält, statt pauschal zehn Minuten pro Block anzunehmen.',
    pl_PL:
      'Szacowana korekta trudności na pulpicie jest teraz dokładna już od samego początku okresu korekty. Wcześniej mierzono czas, który upłynął do bieżącej chwili, licząc jedynie ukończone bloki, więc oczekiwanie od ostatniego bloku, średnio dziesięć minut, było wliczane jako czas kopania, który niczego nie przyniósł. Kilka bloków po rozpoczęciu okresu to oczekiwanie stanowi większość próby, dlatego wartość była na początku mocno błędna i stabilizowała się dopiero mniej więcej w połowie. Teraz pomiar odbywa się między znacznikami czasu bloków, tak jak pokazuje to mempool.space. Szacowany czas do korekty jest wyliczany w tempie, które sieć faktycznie utrzymuje w tym okresie, zamiast zakładać sztywne dziesięć minut na blok.',
    fr_FR:
      'L’ajustement de difficulté estimé sur le tableau de bord est désormais exact dès le tout début d’une période de réajustement. Il mesurait auparavant le temps écoulé jusqu’à l’instant présent tout en ne comptant que les blocs terminés : l’attente depuis le dernier bloc, dix minutes en moyenne, était donc comptabilisée comme du temps de minage n’ayant rien produit. Quelques blocs après le début d’une période, cette attente représente l’essentiel de l’échantillon, ce qui explique pourquoi le chiffre était très faux au début et ne se stabilisait qu’à mi-parcours. La mesure se fait maintenant entre les horodatages des blocs, comme l’affiche mempool.space. Le temps estimé avant l’ajustement est projeté au rythme que le réseau tient réellement sur cette période, au lieu de supposer dix minutes fixes par bloc.',
  },
  // No data migration in either direction. The change is confined to how
  // the service derives one displayed number from data it already fetches
  // from Bitcoin Core; nothing stored changes shape.
  migrations: {},
})
